export const RECOGNITION_START= 'RECOGNITION_START';
export const RECOGNITION_STOP= 'RECOGNITION_STOP';
export const RECOGNITION_FINISH= 'RECOGNITION_FINISH';

export const SYNTHESIS_START= 'SYNTHESIS_START';
export const SYNTHESIS_STARTED= 'SYNTHESIS_STARTED';
export const SYNTHESIS_STOP= 'SYNTHESIS_STOP';

export const TEXT_CHANGE= 'TEXT_CHANGE';

export const API_SELECT= 'API_SELECT';

export const APIS = {
  RECOGNITION: {
    WEB_SPEECH_API: 'WEB_SPEECH_API',
  },
  SYNTHESIS: {
    WEB_SPEECH_API: 'WEB_SPEECH_API',
    AI_TALK: 'AI_TALK'
  },
};

