export default {
  RECOGNITION_START: 'RECOGNITION_START',
  RECOGNITION_STOP: 'RECOGNITION_STOP',
  RECOGNITION_FINISH: 'RECOGNITION_FINISH',

  SYNTHESIS_START: 'SYNTHESIS_START',
  SYNTHESIS_STARTED: 'SYNTHESIS_STARTED',
  SYNTHESIS_STOP: 'SYNTHESIS_STOP',

  TEXT_CHANGE: 'TEXT_CHANGE',

  API_SELECT: 'API_SELECT',

  APIS: {
    RECOGNITION: {
      WEB_SPEECH_API: 'WEB_SPEECH_API',
    },
    SYNTHESIS: {
      WEB_SPEECH_API: 'WEB_SPEECH_API',
      AI_TALK: 'AI_TALK'
    },
  }
};

